version: "3.7"
services:
  backend_server:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: 
      - ./env/backend.env
  frontend_server:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true #view changes on container
    tty: true #view changes on container
    depends_on:
      - backend_server


